//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkVitaOrganization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ZoneSuperVisor
    {
        public int id { get; set; }
        public string name { get; set; }
        public string empIdNo { get; set; }
        public Nullable<int> mobile { get; set; }
        public Nullable<int> zoneId { get; set; }
        public Nullable<int> zoneOfficerId { get; set; }
        public Nullable<int> vanDriverId { get; set; }
    
        public virtual tbl_VanDriverList tbl_VanDriverList { get; set; }
        public virtual tbl_ZoneList tbl_ZoneList { get; set; }
        public virtual tbl_ZoneOfficerList tbl_ZoneOfficerList { get; set; }
    }
}
