//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkVitaOrganization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Price
    {
        public tbl_Price()
        {
            this.tbl_Issue = new HashSet<tbl_Issue>();
        }
    
        public int id { get; set; }
        public int unitId { get; set; }
        public int itemMasterId { get; set; }
        public double price { get; set; }
    
        public virtual ICollection<tbl_Issue> tbl_Issue { get; set; }
        public virtual tbl_ItemMaster tbl_ItemMaster { get; set; }
        public virtual tbl_Unit tbl_Unit { get; set; }
    }
}
