//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkVitaOrganization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Issue
    {
        public int id { get; set; }
        public int GRN { get; set; }
        public int demandNo { get; set; }
        public int itemId { get; set; }
        public int brandId { get; set; }
        public Nullable<int> colorId { get; set; }
        public int demandQty { get; set; }
        public int receiveQty { get; set; }
        public int issueQty { get; set; }
        public int unitId { get; set; }
        public int priceId { get; set; }
        public Nullable<int> departmentId { get; set; }
        public System.DateTime dateTime { get; set; }
        public int calanNo { get; set; }
    
        public virtual tbl_Brand tbl_Brand { get; set; }
        public virtual tbl_Color tbl_Color { get; set; }
        public virtual tbl_Demand tbl_Demand { get; set; }
        public virtual tbl_Demand tbl_Demand1 { get; set; }
        public virtual tbl_Department tbl_Department { get; set; }
        public virtual tbl_ItemMaster tbl_ItemMaster { get; set; }
        public virtual tbl_Price tbl_Price { get; set; }
        public virtual tbl_Receive tbl_Receive { get; set; }
        public virtual tbl_Receive tbl_Receive1 { get; set; }
        public virtual tbl_Unit tbl_Unit { get; set; }
    }
}
