//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkVitaOrganization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Demand
    {
        public tbl_Demand()
        {
            this.tbl_Issue = new HashSet<tbl_Issue>();
            this.tbl_Issue1 = new HashSet<tbl_Issue>();
            this.tbl_Receive = new HashSet<tbl_Receive>();
        }
    
        public int id { get; set; }
        public int demandNo { get; set; }
        public Nullable<int> serialNo { get; set; }
        public int itemId { get; set; }
        public Nullable<int> colorId { get; set; }
        public Nullable<int> brandId { get; set; }
        public int supplierId { get; set; }
        public int demandQty { get; set; }
        public int unitId { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    
        public virtual tbl_Brand tbl_Brand { get; set; }
        public virtual tbl_Color tbl_Color { get; set; }
        public virtual tbl_ItemMaster tbl_ItemMaster { get; set; }
        public virtual tbl_Supplier tbl_Supplier { get; set; }
        public virtual tbl_Unit tbl_Unit { get; set; }
        public virtual ICollection<tbl_Issue> tbl_Issue { get; set; }
        public virtual ICollection<tbl_Issue> tbl_Issue1 { get; set; }
        public virtual ICollection<tbl_Receive> tbl_Receive { get; set; }
    }
}
