//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkVitaOrganization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Department
    {
        public tbl_Department()
        {
            this.tbl_Issue = new HashSet<tbl_Issue>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<tbl_Issue> tbl_Issue { get; set; }
    }
}
