//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkVitaOrganization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ZoneOfficerList
    {
        public tbl_ZoneOfficerList()
        {
            this.tbl_ZoneSuperVisor = new HashSet<tbl_ZoneSuperVisor>();
        }
    
        public int id { get; set; }
        public string serialNo { get; set; }
        public string name { get; set; }
        public string officersId { get; set; }
    
        public virtual ICollection<tbl_ZoneSuperVisor> tbl_ZoneSuperVisor { get; set; }
    }
}
