//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkVitaOrganization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Category
    {
        public tbl_Category()
        {
            this.tbl_Category1 = new HashSet<tbl_Category>();
            this.tbl_ItemMaster = new HashSet<tbl_ItemMaster>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<int> categoryId { get; set; }
    
        public virtual ICollection<tbl_Category> tbl_Category1 { get; set; }
        public virtual tbl_Category tbl_Category2 { get; set; }
        public virtual ICollection<tbl_ItemMaster> tbl_ItemMaster { get; set; }
    }
}
